apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-api
  template:
    metadata:
      labels:
        app: blog-api
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8000"
    spec:
      containers:
      - name: blog-api
        image: destro3998/sre-blog-api:latest
        ports:
        - containerPort: 5000
        - containerPort: 8000  
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
